# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fd7546a876f2bfa3759ed339e7a88ce786547de302fe7477499b9f78d2726ab9c68654917f2e1cedda4ec294f0f93ffc53c6834c01326072a42e193f0577127
  mail_username: clinic1.sparton@gmail.com
  mail_password: terces123

test:
  secret_key_base: 1e060c497d31ddabfd0dda0ec27910a569f0ddd040137032379fab0c3807abe80f75be452866b62867ffe62298ff605ada7617cef1eb08c465bb699ee87bd533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
